---
- name: Doing tasks for host group ansible-tester0
  hosts: ansible-tester0
  gather_facts: no
  tasks:
    - name: Get hostname
      shell: "hostname"

- name: Doing tasks for host group ansible-tester1
  hosts: ansible-tester1
  gather_facts: no
  tasks:
    - name: Get hostname
      shell: "hostname"

- name: Doing tasks for host group ansible-tester2
  hosts: ansible-tester2
  gather_facts: no
  tasks:
    - name: Get hostname
      shell: "hostname"
